wandb_version: 1

exp_name:
  desc: null
  value: PPO.
gym_id:
  desc: null
  value: CartPole-v1
learning_rate:
  desc: null
  value: 0.00025
total_timesteps:
  desc: null
  value: 25000
seed:
  desc: null
  value: 1
torch_deterministic:
  desc: null
  value: true
cuda:
  desc: null
  value: true
capture_video:
  desc: null
  value: true
anneal_lr:
  desc: null
  value: true
track:
  desc: null
  value: true
wandb_project_name:
  desc: null
  value: ppo-implementation-details
wandb_entity:
  desc: null
  value: null
num_envs:
  desc: null
  value: 4
num_steps:
  desc: null
  value: 128
gae:
  desc: null
  value: true
gamma:
  desc: null
  value: 0.99
gae_lambda:
  desc: null
  value: 0.95
num_minibatches:
  desc: null
  value: 4
update_epoches:
  desc: null
  value: 4
norm_adv:
  desc: null
  value: true
clip_coef:
  desc: null
  value: 0.2
clip_vloss:
  desc: null
  value: true
ent_coef:
  desc: null
  value: 0.01
vs_coef:
  desc: null
  value: 0.5
max_grad_norm:
  desc: null
  value: 0.5
target_kl:
  desc: null
  value: null
batch_size:
  desc: null
  value: 512
minibatch_size:
  desc: null
  value: 128
_wandb:
  desc: null
  value:
    code_path: code/PPO.py
    python_version: 3.10.12
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699629347.475785
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      - 35
      4: 3.10.12
      5: 0.16.0
      8:
      - 5
      13: linux-x86_64
